### ISSUE TITLE
Needs a logo

### ISSUE THREAD

**Issue by SSilents** [stevenaeola/progblack_2425#5]
![image](https://github.com/user-attachments/assets/66e0135b-84d5-4c98-b5c8-28b243e95fd2)

**Comment by stevenaeola** [comment]
Nice but the wrong way round. Maybe an SVG version?

**Comment by SSilents** [comment]
![Spinder](https://github.com/user-attachments/assets/241afd2f-b9bc-4656-8ab9-58ccc5927a58)

Heres my best attempt :)
